server:
  port: 8888
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3310/identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 3124
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  service:
    profile: http://localhost:8889/profile