server:
  port: 9000

app:
  api-prefix: /api/v1
  strip-prefix: 2

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8888
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: profile-service
          uri: http://localhost:8889
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=${app.strip-prefix}